// Auto-generated component registry
// This file is generated by scripts/build-registry.ts
// Do not edit manually

export interface ComponentInfo {
  id: string;
  name: string;
  description: string;
  import: string;
  schemaPath?: string;
  propTypes: string[];
  hasSchema: boolean;
}

export type ComponentRegistry = Record<string, ComponentInfo>;

const componentRegistry: ComponentRegistry = {};

export default componentRegistry;

export const componentList = Object.keys(componentRegistry);

export const getComponent = (id: string): ComponentInfo | undefined => {
  return componentRegistry[id];
};

export const getComponentsWithSchemas = (): ComponentInfo[] => {
  return Object.values(componentRegistry).filter(comp => comp.hasSchema);
};
